In [4]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("Lending-company.csv", index_col="StringID")
lending_co_data = data.copy()
lending_co_data.head()

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [ ]:
lending_co_data["Product"]

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [10]:
lending_co_data.iloc[1]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [ ]:
lending_co_data.iloc[1, 3]

'Location 6'

In [12]:
lending_co_data.iloc[:, 2]

StringID
LoanID_1             Female
LoanID_2             Female
LoanID_3               Male
LoanID_4               Male
LoanID_5             Female
                   ...
LoanID_1039            Male
LoanID_1040            Male
LoanID_1041    NotSpecified
LoanID_1042          Female
LoanID_1043    NotSpecified
Name: CustomerGender, Length: 1043, dtype: object

In [13]:
lending_co_data.iloc[1, :]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [14]:
lending_co_data.iloc[:, 3]

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [ ]:
lending_co_data.iloc[[1, 3, 5], :]  # Select multiple rows by index positions

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_6,6,Product A,Male,Location 34,Region 1,NaN,19/04/2019,2200,45,365,3301,4066,15141,Active

In [ ]:
lending_co_data.iloc[:, [1, 3, 5]]  # S elect multiple columns by index positions

               Product     Location  TotalPrice
StringID
LoanID_1     Product B   Location 3     17600.0
LoanID_2     Product D   Location 6         NaN
LoanID_3     Product B   Location 8     16600.0
LoanID_4     Product A  Location 26     17600.0
LoanID_5     Product B  Location 34     21250.0
...                ...          ...         ...
LoanID_1039  Product B  Location 73     17300.0
LoanID_1040  Product A  Location 82         NaN
LoanID_1041  Product A  Location 11     17300.0
LoanID_1042  Product B  Location 26     16300.0
LoanID_1043  Product A  Location 94     17300.0

[1043 rows x 3 columns]