In [2]:
import pandas as pd

In [3]:
filename = "Lending-company.csv"
my_csv_data = pd.read_csv(filename)
my_csv_data

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,1039,LoanID_1039,Product B,Male,Location 73,Region 6,17300.0,29/12/2018,2200,45,365,3251,4743,16617,Finished Payment
1039,1040,LoanID_1040,Product A,Male,Location 82,Region 1,NaN,28/03/2018,2200,45,365,4090,5582,16617,Finished Payment
1040,1041,LoanID_1041,Product A,NotSpecified,Location 11,Region 4,17300.0,26/04/2018,2200,45,365,4051,5143,16617,Finished Payment
1041,1042,LoanID_1042,Product B,Female,Location 26,Region 6,16300.0,25/10/2016,1000,45,365,1930,3462,15617,Finished Payment
1042,1043,LoanID_1043,Product A,NotSpecified,Location 94,Region 6,17300.0,15/05/2019,2200,45,365,4451,4743,16617,Finished Payment

In [4]:
type(my_csv_data)

pandas.core.frame.DataFrame

#Importing data with the index_col parameter

In [5]:
filename = "Lending-company.csv"
my_csv_data = pd.read_csv(filename, index_col="LoanID")
my_csv_data

,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
LoanID,,,,,,,,,,,,,,
1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,LoanID_1039,Product B,Male,Location 73,Region 6,17300.0,29/12/2018,2200,45,365,3251,4743,16617,Finished Payment
1040,LoanID_1040,Product A,Male,Location 82,Region 1,NaN,28/03/2018,2200,45,365,4090,5582,16617,Finished Payment
1041,LoanID_1041,Product A,NotSpecified,Location 11,Region 4,17300.0,26/04/2018,2200,45,365,4051,5143,16617,Finished Payment
1042,LoanID_1042,Product B,Female,Location 26,Region 6,16300.0,25/10/2016,1000,45,365,1930,3462,15617,Finished Payment
1043,LoanID_1043,Product A,NotSpecified,Location 94,Region 6,17300.0,15/05/2019,2200,45,365,4451,4743,16617,Finished Payment

In [6]:
import numpy as np

In [7]:
lending_co_data1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
lending_co_data1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [8]:
lending_co_data2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter=",")
lending_co_data2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [ ]:
lending_co_data_NAN = np.loadtxt(
    "Lending-Company-Numeric-Data-NAN.csv",
    delimiter=";",
    dtype=np.str_,
)

lending_co_data_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']],
      shape=(1043, 6), dtype='<U5')

In [ ]:
lending_co_data_NAN = np.genfromtxt(
    "Lending-Company-Numeric-Data-NAN.csv", delimiter=";"
)
lending_co_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

Partial Cleaning While Importing

In [14]:
lending_co_data_NAN = np.genfromtxt(
    "Lending-Company-Numeric-Data-NAN.csv", delimiter=";"
)
lending_co_data_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [17]:
lending_co_data_NAN = np.genfromtxt(
    "Lending-Company-Numeric-Data-NAN.csv", delimiter=";", skip_header=2
)
lending_co_data_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1041, 6))